window.presentesCasamento = [
  'Air Fryer',
  'Batedeira',
  'Cafeteira',
  'Multiprocessador',
  'Espremedor de Frutas',
  'Liquidificador',
  'Ferro de Passar Roupa',
  'Fruteira',
  'Panela de Arroz Elétrica',
  'Panela de Pressão Elétrica',
  'Ventilador',
  'Purificador de Água',
  'Bandeja Para Café da Manhã',
  'Faqueiro',
  'Frigideira',
  'Jogo de Panelas',
  'Panela de Pipoca',
  'Panela de Pressão',
  'Aparelho de Jantar',
  'Conjunto de Pratos',
  'Panela de Pudim',
  'Conjunto de Xícaras',
  'Jogo de Copos',
  'Jogo de Jarra e Copos',
  'Jogo de Sobremesa',
  'Garrafa de Café',
  'Conjunto de Potes Herméticos de Bambu (Biscoito)',
  'Kit Pote de Vidro',
  'Travessa de Vidro',
  'Jogo de Taças',
  'Porta Temperos',
  'Relógio de Parede',
  'Jogo de Tapetes de Cozinha',
  'Rede de Descanso',
  'Mop',
  'Espelho Corpo Inteiro de Chão',
  'Kit Cesta Organizadora',
  'Dois Travesseiros',
  'Jogo de Toalhas',
  'Jogo de Lençol Casal',
  'Cobre Leito Casal',
  'Almofadas (Beje com Marrom)',
  'Manta',
  'Edredon',
  'Mesa de Passar Roupa',
  'Escada Para Dentro de Casa',
  'Smart TV',
  'Aspirador de Pó',
  'Armário Multiuso',
  'Lâmpadas Inteligentes',
  'Alexa',
  'Fita Led Inteligente',
  'Forno elétrico',
  'Exaustor de Fogão',
  'Churrasqueira',
  'Cadeira de Escritório',
];

window.chaPanela = [
  '6 Colmeias organizadoras dobráveis pequenas',
  'Afiador de facas e Funil',
  'Batedor manual - Fouet - e Pincel culinário',
  'Tabuleiro antiaderente retângulo',
  'Tabuleiro antiaderente redondo',
  'Kit de bacias',
  'Capacho',
  'Coador de café de pano e suporte',
  'Colheres medidoras e copo medidor',
  '3 Panos de prato',
  '3 Panos de prato',
  'Litro de água para geladeira',
  'Litro de água para geladeira',
  '2 Toalhas de mão de cozinha',
  '2 Colheres de pau',
  'Kit concha, colher, escumadeira, espátula silicone',
  'Colher de sorvete, Cortador de pizza e Espátula de bolo',
  'Escorredor de macarrão e de arroz',
  'Formas de silicone pra microondas',
  'Leiteira',
  'Luva térmica',
  'Mixer',
  'Pano de chão 4 ',
  'Peneira pequena, média e grande',
  'Pirex pequeno',
  'Pirex médio',
  'Pirex grande',
  'Pirex com tampa',
  'Kit pote de plástico',
  'Kit pote de plástico',
  'Ralador - descascador 5 em 1',
  'Rolo de Massa',
  'Kit saladeira',
  'Rodo médio',
  'Vassoura piaçava',
  'Toalha de mesa',
  'Toalha de mesa',
  'Jogo americano',
  'Saleiro, Pimenteiro e Paliteiro',
  'Suporte detergente e esponja',
  'Tábua de carne de vidro',
  'Tesoura cozinha',
  'Kit de pegador de massa com 4',
  'Cesto de roupa',
  'Mangueira Mágica',
];

window.chaCaldeirao = [
  'Arroz',
  'Feijão',
  'Óleo',
  'Macarrão',
  'molho de tomate',
  'Açúcar',
  'Sal',
  'Café',
  'Farinha de trigo',
  'Farinha da mandioca',
  'Fermento',
  'Biscoitos',
  'Katchup',
  'Maionese',
  'Pão de forma',
  'Leite em pó',
  'Manteiga',
  'Requeijão',
  'Leite condensado',
  'Creme de leite',
  'Sabonete',
  'Creme dental',
  'Escova de dente',
  'Cotonete',
  'Algodão',
  'Prestobarba',
  'Fio dental',
  'Papel Higiênico',
  'Detergente',
  'Sabão em barra',
  'Esponja',
  'Água Sanitária',
  'Veja',
  'Desinfetante',
  'Sabão em pó',
  '⁠sabão Líquido',
  'Amaciante',
  'Papel Alumínio',
  'Papel Filme',
  'Palito de dente',
  'Filtro de café',
  'Alcool',
];