window.presentesCasamento = [
  "Air Fryer",
  "Batedeira",
  "Cafeteira",
  "Multiprocessador",
  "Espremedor de Frutas",
  "Liquidificador",
  "Ferro de Passar Roupa",
  "Fruteira",
  "Panela de Arroz Elétrica",
  "Panela de Pressão Elétrica",
  "Ventilador",
  "Purificador de Água",
  "Bandeja Para Café da Manhã",
  "Faqueiro",
  "Frigideira",
  "Jogo de Panelas",
  "Panela de Pipoca",
  "Panela de Pressão",
  "Aparelho de Jantar",
  "Conjunto de Pratos",
  "Panela de Pudim",
  "Conjunto de Xícaras",
  "Jogo de Copos",
  "Jogo de Jarra e Copos",
  "Jogo de Sobremesa",
  "Garrafa de Café",
  "Conjunto de Potes Herméticos de Bambu (Biscoito)",
  "Kit Pote de Vidro",
  "Travessa de Vidro",
  "Jogo de Taças",
  "Porta Temperos",
  "Relógio de Parede",
  "Jogo de Tapetes de Cozinha",
  "Rede de Descanso",
  "Mop",
  "Espelho Corpo Inteiro de Chão",
  "Kit Cesta Organizadora",
  "Dois Travesseiros",
  "Jogo de Toalhas",
  "Jogo de Lençol Casal",
  "Cobre Leito Casal",
  "Almofadas (Bege com Marrom)",
  "Manta",
  "Edredom",
  "Mesa de Passar Roupa",
  "Escada Para Dentro de Casa",
  "Smart TV",
  "Aspirador de Pó",
  "Armário Multiuso",
  "Lâmpadas Inteligentes",
  "Alexa",
  "Fita Led Inteligente",
  "Forno Elétrico",
  "Exaustor de Fogão",
  "Churrasqueira",
  "Cadeira de Escritório"
];

window.chaCaldeirao = [
  "Arroz",
  "Feijão",
  "Óleo",
  "Macarrão",
  "Molho de Tomate",
  "Açúcar",
  "Sal",
  "Café",
  "Farinha de Trigo",
  "Farinha de Mandioca",
  "Fermento",
  "Biscoitos",
  "Ketchup",
  "Maionese",
  "Pão de Forma",
  "Leite em Pó",
  "Manteiga",
  "Requeijão",
  "Leite Condensado",
  "Creme de Leite",
  "Sabonete",
  "Creme Dental",
  "Escova de Dente",
  "Cotonete",
  "Algodão",
  "Prestobarba",
  "Fio Dental",
  "Papel Higiênico",
  "Detergente",
  "Sabão em Barra",
  "Esponja",
  "Água Sanitária",
  "Veja",
  "Desinfetante",
  "Sabão em Pó",
  "Sabão Líquido",
  "Amaciante",
  "Papel Alumínio",
  "Papel Filme",
  "Palito de Dente",
  "Filtro de Café",
  "Álcool"
];